const prisma = require('../src/config/db');

const products = [
  // LAPTOPS
  {
    title: 'ASUS Vivobook 15 (2024)',
    brand: 'ASUS',
    category: 'laptop',
    price: 45990,
    originalPrice: 62990,
    discount: 27,
    rating: 4.3,
    reviewCount: 1250,
    description: 'Thin and light laptop with Intel Core i5-1335U 13th Gen, 16GB RAM, 512GB SSD, 15.6" FHD Display, Windows 11 Home, Backlit Keyboard.',
    specifications: { processor: 'Intel Core i5 13th Gen', ram: '16GB DDR4', storage: '512GB M.2 NVMe SSD', display: '15.6 inch FHD (1920x1080)', battery: '42Whr, up to 6 hours', weight: '1.7 kg' },
    amazonLink: 'https://amazon.in/dp/B0CX5W2314',
    flipkartLink: 'https://flipkart.com/asus-vivobook-15/p/itm123',
    cromaLink: 'https://croma.com/asus-vivobook',
    vijayLink: 'https://vijaysales.com/asus-vivobook',
    tags: ['budget', 'student', 'office', 'under50k'],
  },
  {
    title: 'HP Pavilion 14',
    brand: 'HP',
    category: 'laptop',
    price: 52990,
    originalPrice: 71000,
    discount: 25,
    rating: 4.4,
    reviewCount: 980,
    description: 'HP Pavilion 14, Intel Core i5 13th Gen, 16GB RAM, 512GB SSD, 14-inch IPS micro-edge FHD, Intel Iris Xe Graphics, B&O Audio, Fingerprint Reader.',
    specifications: { processor: 'Intel Core i5-1335U', ram: '16GB DDR4', storage: '512GB PCIe SSD', display: '14 inch FHD IPS', battery: '43Whr, Fast Charge', weight: '1.41 kg' },
    amazonLink: 'https://amazon.in/dp/B0C456789',
    flipkartLink: 'https://flipkart.com/hp-pavilion-14',
    cromaLink: 'https://croma.com/hp-pavilion',
    tags: ['compact', 'premium', 'student', 'lightweight'],
  },
  {
    title: 'Lenovo IdeaPad Gaming 3',
    brand: 'Lenovo',
    category: 'laptop',
    price: 58990,
    originalPrice: 85000,
    discount: 30,
    rating: 4.5,
    reviewCount: 2100,
    description: 'AMD Ryzen 5 7535HS, NVIDIA GeForce RTX 3050 4GB, 16GB RAM, 512GB SSD, 15.6" FHD 120Hz Display, Military Grade Durability.',
    specifications: { processor: 'AMD Ryzen 5 7535HS', ram: '16GB DDR5', storage: '512GB SSD', graphics: 'NVIDIA RTX 3050 4GB', display: '15.6 inch FHD 120Hz', weight: '2.3 kg' },
    amazonLink: 'https://amazon.in/dp/B0C987654',
    flipkartLink: 'https://flipkart.com/lenovo-ideapad-gaming',
    tags: ['gaming', 'rtx', 'performance'],
  },
  {
    title: 'Apple MacBook Air M1',
    brand: 'Apple',
    category: 'laptop',
    price: 68990,
    originalPrice: 99900,
    discount: 31,
    rating: 4.8,
    reviewCount: 15400,
    description: 'Apple M1 chip with 8‑core CPU and 7‑core GPU, 8GB RAM, 256GB SSD, 13.3-inch Retina Display, Up to 18 hours battery life.',
    specifications: { processor: 'Apple M1 8-Core', ram: '8GB Unified Memory', storage: '256GB SSD', display: '13.3 inch Retina Display', battery: 'Up to 18 hours', weight: '1.29 kg' },
    amazonLink: 'https://amazon.in/dp/B08N5W4NNB',
    flipkartLink: 'https://flipkart.com/apple-macbook-air-m1',
    cromaLink: 'https://croma.com/macbook-air-m1',
    tags: ['apple', 'macbook', 'premium', 'battery-king'],
  },
  {
    title: 'Acer Aspire Lite',
    brand: 'Acer',
    category: 'laptop',
    price: 31990,
    originalPrice: 47990,
    discount: 33,
    rating: 4.1,
    reviewCount: 650,
    description: 'AMD Ryzen 5 5500U Hexa-Core Mobile Processor, 16GB RAM, 512GB SSD, Windows 11 Home, 15.6" Full HD Metal Body.',
    specifications: { processor: 'AMD Ryzen 5 5500U', ram: '16GB DDR4', storage: '512GB SSD', display: '15.6 inch FHD', weight: '1.6 kg' },
    amazonLink: 'https://amazon.in/dp/B0C123987',
    tags: ['budget', 'entry-level', 'under35k'],
  },

  // SMARTPHONES
  {
    title: 'OnePlus Nord CE 4 5G',
    brand: 'OnePlus',
    category: 'phone',
    price: 24999,
    originalPrice: 26999,
    discount: 7,
    rating: 4.4,
    reviewCount: 3400,
    description: 'Snapdragon 7 Gen 3, 8GB RAM, 128GB Storage, 5500mAh Battery with 100W SUPERVOOC Fast Charging, 50MP Sony LYT-600 Camera with OIS.',
    specifications: { processor: 'Snapdragon 7 Gen 3', ram: '8GB', storage: '128GB', display: '6.7 inch AMOLED 120Hz', camera: '50MP + 8MP | 16MP Front', battery: '5500mAh, 100W Charging' },
    amazonLink: 'https://amazon.in/dp/B0CY12345',
    flipkartLink: 'https://flipkart.com/oneplus-nord-ce-4',
    tags: ['5g', 'fast-charging', 'camera', 'best-seller'],
  },
  {
    title: 'Samsung Galaxy M35 5G',
    brand: 'Samsung',
    category: 'phone',
    price: 18999,
    originalPrice: 24499,
    discount: 22,
    rating: 4.2,
    reviewCount: 1800,
    description: 'Exynos 1380, 120Hz sAMOLED Display with Gorilla Glass Victus+, 6000mAh Battery, Vapor Cooling Chamber.',
    specifications: { processor: 'Exynos 1380', ram: '6GB', storage: '128GB', display: '6.6 inch Super AMOLED 120Hz', battery: '6000mAh' },
    amazonLink: 'https://amazon.in/dp/B0D123456',
    tags: ['samsung', 'battery', 'under20k'],
  },
  {
    title: 'Apple iPhone 15 (128 GB)',
    brand: 'Apple',
    category: 'phone',
    price: 65900,
    originalPrice: 79900,
    discount: 17,
    rating: 4.7,
    reviewCount: 8900,
    description: 'Dynamic Island, 48MP Main camera with 2x Telephoto, USB-C connector, A16 Bionic chip.',
    specifications: { processor: 'Apple A16 Bionic', ram: '6GB', storage: '128GB', display: '6.1 inch Super Retina XDR OLED', camera: '48MP + 12MP' },
    amazonLink: 'https://amazon.in/dp/B0CHX1W1XY',
    flipkartLink: 'https://flipkart.com/apple-iphone-15',
    tags: ['apple', 'flagship', 'camera', 'premium'],
  },

  // AUDIO & HEADPHONES
  {
    title: 'Sony WH-1000XM5 Wireless ANC Headphones',
    brand: 'Sony',
    category: 'audio',
    price: 26990,
    originalPrice: 34990,
    discount: 23,
    rating: 4.6,
    reviewCount: 1400,
    description: 'Industry Leading Noise Cancellation, 8 Mic System, Auto NC Optimizer, 30 Hours Battery Life, Quick Charge.',
    specifications: { type: 'Over-Ear Wireless', anc: 'Industry Leading Active Noise Cancellation', battery: '30 Hours', driver: '30mm specially designed' },
    amazonLink: 'https://amazon.in/dp/B09XS7JWHH',
    tags: ['anc', 'audiophile', 'premium', 'sony'],
  },
  {
    title: 'boAt Nirvana Ion TWS Earbuds',
    brand: 'boAt',
    category: 'audio',
    price: 1799,
    originalPrice: 7990,
    discount: 77,
    rating: 4.1,
    reviewCount: 12000,
    description: '120 Hours Total Playback, Crystal Bionic Sound powered by HiFi DSP, Dual Mic ENx Tech, Low Latency Mode.',
    specifications: { type: 'True Wireless Earbuds (TWS)', battery: '24 hrs per charge, 120 hrs with case', waterResistant: 'IPX4' },
    amazonLink: 'https://amazon.in/dp/B0BY12345',
    tags: ['budget', 'tws', 'battery', 'under2k'],
  },

  // SMART TV
  {
    title: 'LG 108 cm (43 inches) 4K Ultra HD Smart LED TV',
    brand: 'LG',
    category: 'tv',
    price: 30990,
    originalPrice: 49990,
    discount: 38,
    rating: 4.3,
    reviewCount: 2800,
    description: 'α5 AI Processor 4K Gen6, WebOS 23, AI Sound (Virtual 5.1 Up-mix), HDR10 Pro, Apple Airplay 2 & Homekit.',
    specifications: { resolution: '4K Ultra HD (3840x2160)', refreshRate: '60Hz', sound: '20W 2.0 Channel AI Sound', smartFeatures: 'WebOS, Netflix, Prime, Disney+' },
    amazonLink: 'https://amazon.in/dp/B0C345678',
    tags: ['4k', 'smart-tv', 'lg'],
  }
];

async function main() {
  console.log('Seeding shopping catalog...');
  await prisma.product.deleteMany({});
  for (const p of products) {
    await prisma.product.create({ data: p });
  }
  console.log(`Successfully seeded ${products.length} products!`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
